apiVersion: virtink.smartx.works/v1alpha1
kind: VirtualMachine
metadata:
  name: kasm-vps-core
  namespace: default
  labels:
    app: kasm-workspaces-host
spec:
  runPolicy: Always
  template:
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 2
          model: host-passthrough
        memory:
          size: 4Gi
          slots: 1
          maxSize: 8Gi
        features:
          acpi: {}
          apic: {}
          kvm:
            hidden: false
        devices:
          disks:
            - name: system-disk
              bootOrder: 1
              virtio: {}
          interfaces:
            - name: eth0
              bridge: {}
              masquerade: {}
              model: virtio
      volumes:
        - name: system-disk
          containerDisk:
            image: smartxworks/ubuntu-cloudimg:22.04
            imagePullPolicy: IfNotPresent
      networks:
        - name: eth0
          pod: {}
          
